AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw ScatterbugAnimation
	dw SpewpaAnimation
	dw VivillonAnimation
	dw RookideeAnimation
	dw CorvisquirAnimation
	dw PawmotAnimation
	dw FletchlingAnimation
	dw FletchindrAnimation
	dw PidgeotAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw ScolipedeAnimation
	dw ZoroarkAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw SnomAnimation
	dw VenomothAnimation
	dw MudbrayAnimation
	dw MudsdaleAnimation
	dw MeowthAnimation
	dw PerrserkerAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw GreavardAnimation
	dw PrimeapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw RockruffAnimation
	dw PoliwhirlAnimation
	dw LeafeonAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw TimburrAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw YamperAnimation
	dw BoltundAnimation
	dw FarfetchDAnimation
	dw PawmiAnimation
	dw PawmoAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw BlitzleAnimation
	dw ElectrodeAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw HitmonleeAnimation
	dw SigilyphAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw MareanieAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw CapsakidAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw WhirlipedeAnimation
	dw MagmarAnimation
	dw DurantAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw SprigatitoAnimation
	dw FloragatoAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw ArctozoltAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw ShinxAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw SmolivAnimation
	dw DollivAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw AbsolAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw BombirdierAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw MinccinoAnimation
	dw CinccinoAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw ZoruaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw NoibatAnimation
	dw SpiritombAnimation
	dw SmoochumAnimation
	dw VenipedeAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RegirockAnimation
	dw SpectrierAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	assert_table_length NUM_POKEMON
