FramesPointers:
	table_width 2, FramesPointers
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw ScatterbugFrames
	dw SpewpaFrames
	dw VivillonFrames
	dw RookideeFrames
	dw CorvisquirFrames
	dw PawmotFrames
	dw FletchlingFrames
	dw FletchindrFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw SpearowFrames
	dw FearowFrames
	dw EkansFrames
	dw ArbokFrames
	dw LuxioFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw SnomFrames
	dw VenomothFrames
	dw MudbrayFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw RockruffFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw TimburrFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw YamperFrames
	dw MagnetonFrames
	dw FarfetchDFrames
	dw PawmiFrames
	dw PawmoFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw BlitzleFrames
	dw ElectrodeFrames
	dw RioluFrames
	dw LucarioFrames
	dw CuboneFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw CapsakidFrames
	dw ScytherFrames
	dw JynxFrames
	dw WhirlipedeFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw MewFrames
	dw SprigatitoFrames
	dw FloragatoFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw ShinxFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw SmolivFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw MinccinoFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw ZoruaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw VenipedeFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	assert_table_length NUM_POKEMON
